export enum RoutesEnum {
    Home = '/',
    Login = '/login',
    Register = '/register',
    Logout = '/logout',
    Category = '/categories',
    Region = '/regions',
    Tag = '/tags',
    Example = '/example',
    Good = '/goods',
    User = '/users',
    Place = '/places',
    Storage = '/storages',
    Unit = '/units',
}